### ISSUE TITLE
Cant add more that 10 games

### ISSUE THREAD

**Issue by lavilao** [LenAnderson/F95zone-Followed-Games#1]
Hi, everytime I try to add more games it will just override the not finished ones. Am using chromeos if that matters.

**Comment by LenAnderson** [comment]
Can't reproduce. I just followed 12 games and they all showed up.
Check your browser's console for any errors when following new games, check if it happens with all games or only specific ones... Maybe chromeos is extremely restrictive about the amount of local storage allowed to be used and out of space?
